import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Layout/Sidebar";
import TopBar from "./Layout/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex top-0 z-10">
          <Sidebar />
          <div className="flex flex-col w-full">
            <TopBar />
            <div>
              {children}
            </div>
          </div>
        </header>
      </body>
    </html>
  );
}
